### ISSUE TITLE
Relay new user welcome message to IRC?

### ISSUE THREAD

**Issue by bigpresh** [smc87/WildExtras#4]
It would be useful if WIldBot could announce on IRC when a new user joins for the first time - the "Welcome $player to the server" message goes to in-game chat, but doesn't go to IRC.  It's not unusual for no mods (or sometimes anyone at all) to be in-game, but for mods and helpful community members to be on IRC - if they saw that someone was joining for the first time they'd be able to welcome them more easily.

(Lei suggested this!)

**Comment by smc87** [comment]
sounds good. although i guess maybe the pink names you have added sort of remove the need for this.
Still, i will look into it at some point.

**Comment by smc87** [comment]
I'm sorting this out, but via the CraftIRC3 Repo. Done now, but think ive broken colours.

Backup copy still in plugins folder incase of outrage!

**Comment by smc87** [comment]
Think the merge with the latest source fork might fix this (CraftIRC3 repo). leave this open until actually seeing the message come through!! - lazy testing.

**Comment by smc87** [comment]
Done!
